rooms: peterlak.buildrooms.c
	gcc -std=c89 -o peterlak.buildrooms peterlak.buildrooms.c
adv: peterlak.adventure.c
	gcc -std=c89 -o peterlak.adventure peterlak.adventure.c
clean:
	rm -rf *.o peterlak.adventure peterlak.buildrooms peterlak.buildrooms.1* peterlak.buildrooms.2* peterlak.buildrooms.3* peterlak.buildrooms.4* peterlak.buildrooms.5* peterlak.buildrooms.6* peterlak.buildrooms.7* peterlak.buildrooms.8* peterlak.buildrooms.9*
