rooms: peterlak.buildrooms.c
	gcc -std=c89 -o peterlak.buildrooms peterlak.buildrooms.c
adv: peterlak.adventure.c
	gcc -std=c89 -o peterlak.adventure peterlak.adventure.c
clean:
	sudo rm -rf *.o peterlak.adventure peterlak.buildrooms peterlak.buildrooms.1*
