keygen: keygen.c
	gcc -std=gnu11 -o keygen keygen.c
otp_enc_d: otp_enc_d.c
	gcc -std=gnu11 -o otp_enc_d otp_enc_d.c
otp_enc: otp_enc.c
	gcc -std=gnu11 -o otp_enc otp_enc.c
otp_dec_d: otp_dec_d.c
	gcc -std=gnu11 -o otp_dec_d otp_dec_d.c
otp_dec: otp_dec.c
	gcc -std=gnu11 -o otp_dec otp_dec.c
clean:
	rm -rf *.o keygen otp_enc_d otp_enc otp_dec_d otp_dec
